2025-03-05 14:56:51,265 - INFO - ‚úÖ Using GPU device 1.
2025-03-05 14:56:51,266 - WARNING - ‚ö†Ô∏è Output directory 'NPZ' does not exist: /path/to/your/output/npz
2025-03-05 14:56:51,267 - INFO - üìÅ Output directory 'NPY' is set to: /caefs/data/IllustrisTNG/300/ICS
2025-03-05 14:56:51,267 - WARNING - ‚ö†Ô∏è Output directory 'LOGS' does not exist: /path/to/your/logs
2025-03-05 14:56:51,267 - ERROR - Unhandled exception occurred:
Traceback (most recent call last):
  File "visualization_ex.py", line 16, in <module>
    from data_loader import DataLoader
  File "/caefs/user/mmingyeong/structura/Structura/src/data_loader.py", line 19, in <module>
    class DataLoader:
  File "/caefs/user/mmingyeong/structura/Structura/src/data_loader.py", line 39, in DataLoader
    ) -> np.ndarray | None:
TypeError: unsupported operand type(s) for |: 'type' and 'NoneType'
